config/routes.rb
Schizoworld::Application.routes.draw do

  resources :announces
  resources :messages

  match '/activate/:activation_code' => 'users#activate', :as => :activate, :activation_code => nil

  resource :session, :only => [:new, :create, :destroy, :provider, :failure]
  resources :sessions
  resources :users
  resources :projects do
    resources :posts
  end
  
  resources :videos do
  member do
    post :add_comment
  end
  new do
     post :upload
     get :save_video
   end
  end

  match "videos/:id/add_comment", :to => "videos#add_comment"

  match 'login' => 'sessions#new', :as => :login
  match 'logout' => 'sessions#destroy', :as => :logout
  match 'signup' => 'users#new', :as => :signup
  match 'register' => 'users#create', :as => :register

  match '/auth/:provider/callback', :to => 'sessions#provider'
  match '/auth/failure', :to => 'sessions#failure'

  match 'profile' => 'users#index', :as => :profile

  match '/messages' => 'messages#create', :via => :post
  match '/messages', :to => 'messages#inbox'
  get 'messages/autocomplete_user_login'
  match '/messages/show/:id', :to => 'messages#show'
  match '/messages/inbox', :to => 'messages#inbox'
  match '/messages/sentbox', :to => 'messages#sentbox'
  match '/messages/trash', :to => 'messages#trash'
  match '/messages/new', :to => 'messages#new'
  
  match ':controller(/:action(/:id(.:format)))'
  
  root :to => "application#index"

end

app/models/message.rb
class Message < ActiveRecord::Base
  #any additional info that needs to be sent in a message (ex. I use these to determine request types)
  serialize :headers
  
  class_inheritable_accessor :on_deliver_callback
  protected :on_deliver_callback
  
  belongs_to :sender, :class_name => 'User', :foreign_key => 'sender_id'
  belongs_to :conversation
  has_and_belongs_to_many :recipients, :class_name => 'User', :join_table => 'messages_recipients', :association_foreign_key => 'recipient_id'
  
  #delivers a message to the the given mailbox of all recipients, calls the on_deliver_callback if initialized.
  #
  #====params:
  #mailbox_type:: the mailbox to send the message to
  #clean:: calls the clean method if this is set (must be implemented)
  #
  def deliver(mailbox_type, clean = true)
    clean() if clean
    self.save()
    self.recipients.each do |r|
      r.mailbox[mailbox_type] << self
    end
    self.on_deliver_callback.call(self, mailbox_type) unless self.on_deliver_callback.nil?
  end
  
  #sets the on_deliver_callback to the passed method. The method call should expect 2 params (message, mailbox_type).
  def Message.on_deliver(method)
    self.on_deliver_callback = method
  end
  
  protected
  #[empty method]
  #
  #this gets called when a message is delivered and the clean param is set (default). Implement this if you wish to clean out illegal content such as scripts or anything that will break layout. This is left empty because what is considered illegal content varies.
  def clean()
    #strip all illegal content here. (scripts, shit that will break layout, etc.)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  autocomplete :user, :login

  # GET /messages AND /messages/inbox
  def inbox
    if !current_user.nil?
      @mailbox = current_user.mailbox
      respond_to do |format|
        format.html # inbox.html.erb
        format.json { render json: @messages }
      end
    else
      redirect_to "/"
    end
  end

  def sentbox
    if current_user
      respond_to do |f|
        f.html # sentbox.html.erb
        f.json { render json: @mailbox.messages }
      end
    else
      redirect_to "/"
    end
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
    mail = Mail.find(params[:id])

    if mail
      @conversation = mail.conversation
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @conversation }
      end
    end
  end

  # POST /messages
  # POST /messages.json
  def create
    # @TODO:
    # récupérer les infos de messages/_form ici et faire le send_mail en conséquence !
    recipients = []
    if params[:to_uid].is_a?(Array)
      params[:to_uid].each do |r|
        recipients[] = User.find(r)
      end
    elsif !params[:to_uid].nil?
      recipients[] = User.find(params[:to_uid])
    end
    if recipients.empty?
      if !!params[:reply_to]
        current_user.reply_to_all(Mail.find(:reply_to))
      end
    else
      current_user.send_message(recipients, params[:body])
    end

    redirect_to '/messages'
  end

  def reply
    mail = Mail.find(params[:mail_id])
    if !mail.nil? && !current_user.nil?
      current_user.reply_to_all(mail, params[:mail])
    end
  end

  # GET /messages/new
  # GET /messages/new?embedded=1
  def new
    #if(params[embedded] == 1)
      render :partial => "messages/embedded" 
    #
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_embedded.html.erb
<style type="text/css">
	#new_message_form {
		border: 1px red solid;
	}
</style>
<div id="new_message_form">
	<%= render :partial => "form" %>
</div>

app/views/messages/_form.html.haml
= form_tag "/messages", :html => {:id => "new_form"} do
  .field
    = label_tag(:to, "Destinataire")
    = autocomplete_field_tag :to, '', messages_autocomplete_user_login_path, :id_element => '#to_uid'
    = hidden_field_tag :to_uid
  .field
    = label_tag :body, 'Message'
    = text_area_tag :body, '', :size => "30x5"
  .actions
    = submit_tag 'Envoyer'

app/views/messages/_new_button.html.erb
<%= link_to 'Nouveau message', "#", :onclick => "$('#new_message_box').toggle()", :class => "new_message" %>
<div id="new_message_box" style="display:none"> 
	<%= render :partial => "form" %>
</div>

app/views/messages/_sidebar_nav.html.haml
.yui-b.sidebar
  -box do 
    %h3= :links.l
    %ul.message_nav
      %li{:class => "inbox#{@user.unread_messages? ? '_new': ''}"}
        = link_to :inbox.l, user_messages_path(@user)
        = "(#{@user.unread_message_count})" if @user.unread_messages?
      %li.sent= link_to :sent_messages.l, user_messages_path(@user, :mailbox => :sent)
      %li.compose= link_to :compose.l, new_user_message_path(@user)

app/views/messages/edit.html.haml
%h1 Editing message

= render 'form'

= link_to 'Show', @message
\|
= link_to 'Back', messages_path

app/views/messages/inbox.html.haml
%br
%br
%br
%br
%h1 Messages reçus

%br
- if @mailbox.latest_mail.nil? || @mailbox.latest_mail.empty?
  %p Aucun nouveau message.
- else
  %h2 Messages
  %table

    %tr
    - @mailbox.latest_mail.each do |mail|
      %tr
        %td
          - if !mail.read
            %span{:class => 'ui-icon ui-icon-bullet'} 
        %td{:style=>"padding-right: 40px"}= mail.message.sender.login
        %td= link_to mail.message.body, "messages/show/" + mail.id.to_s

%br


= render :partial => "new_button"

app/views/messages/index.html.haml
=render :partial => 'messages/sidebar_nav'

- if params[:mailbox] == "sent"
  = form_tag delete_selected_user_messages_path(@user), :class => "MainForm" do
    = render :partial => "sent"
- else
  = form_tag delete_message_threads_user_messages_path(@user), :class => "MainForm" do
    = render :partial => "inbox"

app/views/messages/new.html.haml
%br
%br
%br
%br
%h1 New message

= render 'form'

= link_to 'Back', messages_path

app/views/messages/sentbox.html.haml
%br
%br
%br
%br
%h1 Messages envoyés

- if @messages.nil? || @messages.empty?
  %p Aucun nouveau message.
- else
  %table
    %tr
      %th
      %th
      %th
    %tr
    - @messages.each do |message|
      %tr
        %td= link_to 'Show', message
        %td
        %td



= render :partial => "new_button"

app/views/messages/show.html.erb
<br/><br/><br/><br/>
<p id="notice"><%= notice %></p>
<h1>Conversation avec</h1>
<% @conversation.recipients.each do |r| -%>
  <%= image_tag r.url_img << "=small", :title => r.login, :alt => r.login, :class => "left thumb_facebook" %>
<% end -%>
<div id="conversation">
<% 
  @conversation.messages.each do |message|
    sender = message.sender
%>
  <p class="left" style="margin-left: 5px; padding-right: 40px">
    <a href="<%= user_path(message.sender) %>">
<% if sender.url_img != nil -%>
  <%= image_tag sender.url_img << "=small", :title => sender.login, :alt => sender.login, :class => "left thumb_facebook" %>
<% else -%>
 <%= image_tag sender.avatar.url(:thumb), :title => sender.login, :class => "left" %>
<% end -%>
  <%= sender.login %>
    </a>
  </p>
  <p class="left">
    <%= message.body %>
  </p>
  <div class="clear"></div>
<%  end -%>
</div>
<div id="reply_message">
  <%= form_tag "/messages", :html => {:id => "new_form"} %>
  <div class="field">
  <%= label_tag(:to, "Destinataire") %>
  <%= autocomplete_field_tag :to, '', messages_autocomplete_user_login_path, :id_element => '#to_uid' %>
  <%= hidden_field_tag :to_uid %>
  </div>
  <div class="field">
  <%= label_tag :body, 'Message' %>
  <%= text_area_tag :body, '', :size => "30x5" %>
  <div class="actions">
  <%= submit_tag 'Envoyer' %>
  </div>

</div>

app/views/messages/trash.html.haml
%br
%br
%br
%br
%h1 Messages supprimés

- if @messages.nil? || @messages.empty?
  %p Aucun nouveau message.
- else
  %table
    %tr
      %th
      %th
      %th
    %tr
    - @messages.each do |message|
      %tr
        %td= link_to 'Show', message
        %td
        %td

%br

= link_to 'New Message', "#", :class => "new_message"