config/routes.rb
Schizoworld::Application.routes.draw do

  resources :announces
  resources :messages

  match '/activate/:activation_code' => 'users#activate', :as => :activate, :activation_code => nil

  resource :session, :only => [:new, :create, :destroy, :provider, :failure]
  resources :sessions
  resources :users
  resources :projects do
    resources :posts
  end
  
  resources :videos do
  member do
    post :add_comment
  end
  new do
     post :upload
     get :save_video
   end
  end

  match "videos/:id/add_comment", :to => "videos#add_comment"

  match 'login' => 'sessions#new', :as => :login
  match 'logout' => 'sessions#destroy', :as => :logout
  match 'signup' => 'users#new', :as => :signup
  match 'register' => 'users#create', :as => :register

  match '/auth/:provider/callback', :to => 'sessions#provider'
  match '/auth/failure', :to => 'sessions#failure'

  match 'profile' => 'users#index', :as => :profile

  match '/messages' => 'messages#create', :via => :post
  match '/messages', :to => 'messages#inbox'
  get 'messages/autocomplete_user_login'
  match '/messages/show/:id', :to => 'messages#show'
  match '/messages/inbox', :to => 'messages#inbox'
  match '/messages/sentbox', :to => 'messages#sentbox'
  match '/messages/trash', :to => 'messages#trash'
  match '/messages/new', :to => 'messages#new'
  
  match ':controller(/:action(/:id(.:format)))'
  
  root :to => "application#index"

end

app/models/video.rb
class Video < ActiveRecord::Base
  acts_as_commentable
  
  attr_accessor :comment
  
  scope :completes,   where(:is_complete => true)
  scope :incompletes, where(:is_complete => false)
  
  def create_comment(comment)
    begin
      comments.create(:comment => comment)
      Video.yt_session.add_comment(yt_video_id, comment)
    rescue
      false
    end
  end
    
  def self.yt_session
    @yt_session ||= YouTubeIt::Client.new(:username => YouTubeITConfig.username , :password => YouTubeITConfig.password , :dev_key => YouTubeITConfig.dev_key)    
  end

  def self.delete_video(video)
    yt_session.video_delete(video.yt_video_id)
    video.destroy
      rescue
        video.destroy
  end

  def self.update_video(video, params)
    yt_session.video_update(video.yt_video_id, video_options(params))
    video.update_attributes(params)
  end

  def self.token_form(params, nexturl)
    yt_session.upload_token(video_options(params), nexturl)
  end

  def self.delete_incomplete_videos
    self.incompletes.map{|r| r.destroy}
  end

  private
    def self.video_options(params)
      opts = {:title => params[:title],
             :description => params[:description],
             :category => "People",
             :keywords => ["test"]}
      params[:is_unpublished] == "1" ? opts.merge(:private => "true") : opts
    end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  
  def new
    @project = Project.find(params[:project_id])
    @video = Video.new
    @nodes = get_tree(0)
  end

  def show
    @video = Video.find(params[:id])
 
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @video }
    end
  end
  
  def upload
    @video = Video.create(params[:video])
    @video.update_attribute(:parent_id, params[:parent_id])
    @project = Project.find(params[:video][:project_id])
    if @video
      @upload_info = Video.token_form(params[:video], save_video_new_video_url(:video_id => @video.id))
      @project.update_attribute(:status, "Fini")
    else
      respond_to do |format|
        format.html { render "/videos/new" }
      end
    end
  end

  def update
    @video     = Video.find(params[:id])
    @result    = Video.update_video(@video, params[:video])
    respond_to do |format|
      format.html do
        if @result
          redirect_to @video, :notice => "video successfully updated"
        else
          respond_to do |format|
            format.html { render "/videos/_edit" }
          end
        end
      end
    end
  end

  def save_video
    @video = Video.find(params[:video_id])
    if params[:status].to_i == 200
      @video.update_attributes(:yt_video_id => params[:id].to_s, :is_complete => true)
      Video.delete_incomplete_videos
      nodes = get_tree(0)
      File.open("public/js/libs/tree_data.json", "w"){ #Specifier ou créer le fichier
        |f| f.write(nodes.to_json # Ecrire dans le fichier le tableau "nodes" précédement créé.
      )}
    else
      Video.delete_video(@video)
    end
    redirect_to "/", :notice => "video successfully uploaded"
  end

  def destroy
    @video = Video.find(params[:id])
    if Video.delete_video(@video)
      flash[:notice] = "video successfully deleted"
    else
      flash[:error] = "video unsuccessfully deleted"
    end
    redirect_to videos_path
  end

  def add_comment
    @video = Video.find(params[:id])
    @project = Project.find(params[:video][:project_id])
    @video.create_comment(params[:video][:comment])
    @video.comments.last.update_attribute(:user_id, params[:video][:user_id])
    #if @video.create_comment(params[:video][:comment])
    #  flash[:notice] = "Comment has been sucessfully added."
    #else
    #  flash[:error] = "Sorry the comment has not been added."
    #end
    redirect_to project_path(@project, :public => true)  
  end

  def has_child(id)
    if (Video.exists?(Video.find_by_parent_id(id)))
      result = true
    else
      result = false
    end
    return result
  end
    
  def get_tree(id)
    
    childrens = Video.where(:parent_id => id)
    elements = Array.new
    
    childrens.each do |video|

      project = Project.find(video.project_id)
      img = project.avatar_project_file_name
      img_url = "/system/avatar_projects/" + video.project_id.to_s + "/small/" + img

      if (has_child(video.id))
         element = {'id' => video.id, 'name' => video.title, 'data' => {"url" => img_url, "description" => video.description}, 'children' => get_tree(video.id) }
      else
         element = {'id' => video.id, 'name' => video.title, 'data' => {"url" => img_url, "description" => video.description}, 'children' => [] }
      end
      
      elements << element
      
    end
      
    return elements      
  end
  
  protected
    def collection
      @videos ||= end_of_association_chain.completes
    end

end

app/views/videos/_children.html.erb
<%= @video %>

app/views/videos/_footer.html.haml
%footer#social
  #grass_footer
  #grass_root_footer
  %p It's a small schizophrenic world
  %p
    fork me on
    %a{:href => "http://github.com/Schizo-World"} GitHub

app/views/videos/_form.html.erb
  <div class="group">
    <div class="dhtmlxTree" id="treeboxbox_tree" setImagePath="/js/dhtmlxTree/dhtmlxTree/codebase/imgs/csh_dhx_skyblue/" style="width:250px;height:218px;overflow:auto;float:left;">
      <ul>
        <%  @nodes.each do |node| %>
          <li>
            <%= node['title'] %> 
            <%= radio_button_tag 'parent_id', node['id'] %>
            <%= render :partial => "video", :locals => {:children => node} %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>

  <div id="info_video">
    <div class="field">
      <%= f.label :title, t("activerecord.attributes.video.title", :default => "Titre"), :class => :label %>
      <%= f.text_field :title, :class => 'text_field', :value => @project.name %>
    </div>

    <div class="field">
      <%= f.label :description, t("activerecord.attributes.video.description", :default => "Description"), :class => :label %>
      <%= f.text_area :description, :class => 'text_field', :value => @project.description %>
    </div>

    <div class="field">
      <%= f.hidden_field(:project_id, :value => @project.id)%>
    </div>

    <div class="field">
    <% if @video.new_record?%>
      <button class="field" type="submit">
        <%= image_tag("web-app-theme/icons/tick.png", :alt => "#{t("web-app-theme.save", :default => "Sauvegarder la vidéo")}") %> <%= t("web-app-theme.save", :default => " ") %>
      </button>
    <%else%>
      <button class="field" type="submit">
        <%= image_tag("web-app-theme/icons/tick.png", :alt => "#{t("web-app-theme.save", :default => "Sauvegarder la vidéo")}") %> <%= t("web-app-theme.save", :default => " ") %>
      </button>
    <%end%>

      <span class="text_button_padding"><%= t("web-app-theme.or", :default => " ou ") %></span>
    	<%= link_to t("web-app-theme.cancel", :default => "Annuler"), videos_path, :class => "text_button_padding link_button" %>
    </div>
  </div>

app/views/videos/_show.html.erb
  <p>
    <%= raw yt_client.my_video(@video.yt_video_id).embed_html %>
  </p>
  <!--<h3><%= @video.description %></h3>
  <p><b>url:</b> <a href="http://www.youtube.com/watch?v=<%= @video.yt_video_id %>&feature=youtube_it" target="_blank">http://www.youtube.com/watch?v=<%= @video.yt_video_id %></a></p>

  <div class="wat-cf">
    <%= link_to image_tag("web-app-theme/icons/application_edit.png", :alt => "#{t("web-app-theme.edit", :default=> "Edit")}") + " " + t("web-app-theme.edit", :default=> "Edit"), edit_video_path(@video), :class => "button" %> 
    <%= link_to image_tag("web-app-theme/icons/cross.png", :alt => "#{t("web-app-theme.delete", :default=> "Delete")}") + " " + t("web-app-theme.delete", :default => "Delete"), video_path(@video), :method => "delete", :class => "button", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
  </div>      -->

  <div id="comments">
    <ul>        
      <% @video.comments.each do |c| %>
        <li>
          <div class="item" style="margin-left: 8px !important;">
            <% user = User.find(c.user_id) %>
            <% if user.url_img != nil%>
              <a href="<%= :profile %>"><%= image_tag user.url_img + "=small", :alt => user.login, :class => "img_sheet" %></a>
            <% else %>
              <a href="<%= :profile %>"><%= image_tag user.avatar.url(:small), :class => "img_sheet" %></a>
            <% end %>
            <p class="comment_date right">le <%= c.created_at.strftime("%m/%d/%Y") %></p>
            <p class="comment_login"><%= user.login %> </p>
            <p><%= c.comment %></p>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
  <div class="clear"></div>

  <% if !current_user.nil? %>
    <div id="add_comment">
      <% @user = current_user %>
      <%= form_for @video, :url => add_comment_video_path(@video), :html => { :class => :edit_video } do |f| -%>
        <div class="field">
          <% if @user.url_img != nil%>
            <a href="<%= :profile %>"><%= image_tag @user.url_img + "=small", :alt => @user.login, :class => "img_sheet" %></a>
          <% else %>
            <a href="<%= :profile %>"><%= image_tag @user.avatar.url(:small), :class => "img_sheet" %></a>
          <% end %>
          <%= f.text_area :comment, :class => 'text_area', :rows => 10, :value => "Ecrivez ce que vous en pensez..." %>
        </div>

        <div class="field">
          <%= f.hidden_field(:project_id, :value => @project.id)%>
        </div>
        <div class="field">
          <%= f.hidden_field(:user_id, :value => @user.id)%>
        </div>
        <%= f.submit "Ajouter un commentaire"%>
      <% end -%>
    </div>
  <% end %>
  <br/><br/>

app/views/videos/_show_all.html.erb
<%# <% @videos.each do |video| %>
<%# <% end %>

app/views/videos/_sidebar.html.erb
<div class="block notice">
  <h3>YouTube IT Demo</h3>
  <p>Using youtube_it gem you can do:</p>
  <div class="content">
    <p>Upload your video to YouTube from here!.</p>
    <p>Add, Delete, Update videos from here and see the changes on YouTube site.</p>
    <p>Add comments to yours videos.</p>
  </div>
</div>

app/views/videos/_video.html.erb
<% if !children['children'].empty? %>
  <ul>
    <% children['children'].each do |c| %>
      <li>
        <%= c['title'] %>
        <%= radio_button_tag 'parent_id', c['id'] %>
        <%= render :partial => "video", :locals => {:children => c} %>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/videos/edit.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", videos_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_video_path %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_video_path %></li>
    </ul>
  </div>          
  <div class="content">            
    <h2 class="title"><%= t("web-app-theme.edit", :default => "Edit") %> Video</h2>
    <div class="inner">
      <%= form_for @video, :url => video_path(@video), :html => { :class => :form } do |f| -%>
        <%= render :partial => "form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/videos/index.html.erb
<div id="container" class="socialContainer">
  <div class="block">
    <div class="secondary-navigation">
      <ul class="wat-cf">
        <li class="first active"><%= link_to "#{t("web-app-theme.list", :default => "List")}", videos_path  %></li>
        <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_video_path %></li>
      </ul>
    </div>          
    <div class="content">          
      <h2 class="title"><%= t("web-app-theme.all", :default => "All")  %> Videos</h2>
      <div class="inner">
        <table class="table">
          <tr>             
            <th class="first">ID</th>
                      <th>
              <%= t("activerecord.attributes.video.title", :default => t("activerecord.labels.title", :default => "Title")) %>
            </th>
                      <th><%= t("web-app-theme.created_at", :default => "Created at")  %></th>
            <th class="last">&nbsp;</th>
          </tr>
          <% @videos.each do |video| -%>
          <tr class="<%= cycle("odd", "even") %>">
            <td>
              <%= video.id %>
            </td>
                      <td>
              <%= link_to video.title, video_path(video) %>
            </td>
                      <td>
              <%= video.created_at %>
            </td>
            <td class="last">
              <%= link_to "#{t("web-app-theme.show", :default => "Show")}", video_path(video) %> |
              <%= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_video_path(video) %> |
              <%= link_to "#{t("web-app-theme.delete", :default => "Delete")}", video_path(video), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
            </td>
          </tr>          
          <% end -%>
        </table>
        <div class="actions-bar wat-cf">
          <div class="actions">
          </div>

        </div>
      </div>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/videos/new.html.erb
<div id="sky">
  <div id="container" class="socialContainer">
    <a href="<%=project_path(@project)%>">
      <img class="img_sheet" src="<%= @project.avatar_project.url(:large) %>" alt="<%= @project.name %>"/>
    </a>
    <h1><%= link_to @project.name, project_path(@project) %></h1>

    <div class="left info_sup">
      <div class="info">
        <img src="/img/icons/pencil.png" alt="" class="left"/>
        <p><%=link_to 'Editer la fiche projet', edit_project_path(@project)%></p>
      </div>
      <div class="info">
        <img src="/img/icons/file.png" alt="" class="left"/>
        <p><%=link_to 'Voir la fiche publique', :controller => "projects", :action => "show", :public => true%></p>
      </div>
      <% video = Video.where("project_id = ?", @project.id) %>
      <% if video.blank? %>
        <div class="info">
          <img src="/img/icons/film.png" alt="" class="left"/>
          <p><%=link_to 'Ajouter la vidéo', :controller => "videos", :action => "new", :project_id => @project.id%></p>
        </div>
      <% end %>
      <br/><br/>

      <% if @project.city %>
        <div class="info">
          <img src="/img/icons/location.png" alt="" class="left"/>
          <p><%= @project.city %></p> 
        </div>
      <%end%>

      <% if @project.status %>
        <div class="info">
          <img src="/img/icons/process.png" alt="" class="left"/>
          <p><%= @project.status %></p> 
        </div>
      <%end%>  
      <br/>

      <div class="project_members">
        <% for user in @project.users%>
            <% if user.url_img != nil%>
              <a href="<%= user_path(user.id) %>"><%= image_tag user.url_img + "=small", :alt => user.login, :class => "left thumb_facebook" %></a>
            <% else %>
              <a href="<%= user_path(user.id) %>"><%= image_tag user.avatar.url(:thumb), :class => "left" %></a>
            <% end %>
            <p class="left"><a href="<%= user_path(user) %>"><%= user.login %></a></p>
            <div class="clear"></div>
        <% end %>  
      </div>

    </div>

    <div id="social_content" class="right">
      <div id="socialMenu">
        <ul id="tabs">
          <li>
            <a alt="#communicate" class="tab_menu"> Communiquer </a>
          </li>
          <!--<li>
            <a alt="#doc" class="tab_menu"> Documents </a>
          </li>-->
          <li>
            <a alt="#ad" class="tab_menu"> Nos annonces </a>
          </li>
        </ul>
      </div>

      <div id="content">
        <div id="form">
          <h4>Ajouter la vidéo - Etape 1 </h4>
          <%= form_for @video, :url => upload_new_video_path, :html => { :class => :form } do |f| -%>
            <%= render :partial => "form", :locals => {:f => f} %>
          <% end -%>
          <div class="clear"></div>

        </div>

        <div id="communicate" class="tab_content hidden">
          <div class="write_msg">
            <% if current_user.url_img != nil%>
              <a href="<%= user_path(current_user) %>"><%= image_tag current_user.url_img << "=small", :alt => current_user.login, :class => "left" %></a>
            <% else %>
              <a href="<%= user_path(current_user) %>"><%= image_tag current_user.avatar.url(:small), :class => "left" %></a>
            <% end %>
            <%= form_for(@project) do |f| %>
              <%= f.text_area :message, :value => "Rédiger un message..." %>
            <% end %>
          </div>
        </div>

        <div id="doc" class="tab_content hidden">
          <p>documents</p>
        </div>

        <div id="ad" class="tab_content hidden">
          <% admin = false %>
          <% members = @project.users.where("admin = ?", true) %>
          <% for member in members %>
            <% if member.id == current_user.id %>
              <% admin = true %>
            <% end %>
          <% end %>
          <% if admin == true %>
            <%= render :partial => "announces/new", :locals => {:@announce => Announce.new, :@author_type => '1', :@author_id => @project.id} %>
          <% end %>
          <div class="clear"></div>
          <%if !@announces.blank?%>
              <div id="announces">
                  <h4>Mes annonces</h4>
                    <% for announce in @announces %>
                      <% candidates = AnnounceCandidate.where("announce_id = ?", announce.id) %>
                      <% singular_sentence = "candidat a postulé" %>
                      <% plural_sentence = "candidats ont postulé" %>
                      <% negative_sentence = "Aucun candidat n'a postulé" %>
                      <% if candidates.count == 0 %>
                        <% sentence = negative_sentence %>
                      <% elsif candidates.count == 1 %>
                        <% sentence = "#{candidates.count} " << singular_sentence %>
                      <% else %>
                        <% sentence = "#{candidates.count} " << plural_sentence %>
                      <% end %>
                      <% available = false %>
                      <% for candidate in candidates %>
                        <% if candidate.accepted %>
                          <% available = true %>
                        <% end %>
                      <% end %>
                      <% idcss = "#{announce.id}" %>

                      <div class="announce">
                          <a href="<%= project_path(@project) %>">
                            <%= image_tag @project.avatar_project.url(:medium), :class => "left"%>
                          </a>
                          <p class="send_mail"><img src="#" alt=""/>
                            <% if candidates.count > 0 && available == false%>
                              <%= link_to sentence, "##{announce.id}", :class => "popup" %>
                            <% elsif available == true %>
                              <span class="left">Pourvu</span>
                            <% else %>
                              <%= sentence %>
                            <% end %>
                          </p>
                          <div>
                            <h3><%= announce.title%></h3>
                            <% job = Job.find(announce.job_id) %>
                            <p>
                                <span>#<%= job.label %></span>
                            </p>
                            <p>
                                <img src="/img/icons/location.png" alt=""/>
                                <span><%= announce.location %></span>
                            </p>
                            <p class="description"><%= announce.description %></p>
                            <div class="clear"></div>
                          </div>
                      </div>
                      <% if candidates.count > 0 %>
                        <div style="display: none;">
                          <div id="<%= idcss %>" class="manage_candidates">
                            <%= render :partial => "announces/candidates", :locals => {:@announce_id => announce.id}%>
                          </div>
                        </div>
                      <% end %>
                      <div class="clear"></div>
                    <% end %>
            </div>
          <% end %>
        </div>

      </div>
    </div>
    <div class="clear"></div>
  </div>
</div>

app/views/videos/upload.html.erb
<div id="sky">
  <div id="container" class="socialContainer">
    <a href="<%=project_path(@project)%>">
      <img class="img_sheet" src="<%= @project.avatar_project.url(:large) %>" alt="<%= @project.name %>"/>
    </a>
    <h1><%= link_to @project.name, project_path(@project) %></h1>

    <div class="left info_sup">
      <div class="info">
        <img src="/img/icons/pencil.png" alt="" class="left"/>
        <p><%=link_to 'Editer la fiche projet', edit_project_path(@project)%></p>
      </div>
      <div class="info">
        <img src="/img/icons/file.png" alt="" class="left"/>
        <p><%=link_to 'Voir la fiche publique', :controller => "projects", :action => "show", :public => true%></p>
      </div>
      <% video = Video.where("project_id = ?", @project.id) %>
      <% if video.blank? %>
        <div class="info">
          <img src="/img/icons/film.png" alt="" class="left"/>
          <p><%=link_to 'Ajouter la vidéo', :controller => "videos", :action => "new", :project_id => @project.id%></p>
        </div>
      <% end %>
      <br/><br/>

      <% if @project.city %>
        <div class="info">
          <img src="/img/icons/location.png" alt="" class="left"/>
          <p><%= @project.city %></p> 
        </div>
      <%end%>

      <% if @project.status %>
        <div class="info">
          <img src="/img/icons/process.png" alt="" class="left"/>
          <p><%= @project.status %></p> 
        </div>
      <%end%>  
      <br/>

      <div class="project_members">
        <% for user in @project.users%>
            <% if user.url_img != nil%>
              <a href="<%= user_path(user.id) %>"><%= image_tag user.url_img + "=small", :alt => user.login, :class => "left thumb_facebook" %></a>
            <% else %>
              <a href="<%= user_path(user.id) %>"><%= image_tag user.avatar.url(:thumb), :class => "left" %></a>
            <% end %>
            <p class="left"><a href="<%= user_path(user) %>"><%= user.login %></a></p>
        <% end %>  
      </div>

    </div>

    <div id="social_content" class="right">
      <div id="socialMenu">
        <ul id="tabs">
          <li>
            <a alt="#communicate" class="tab_menu"> Communiquer </a>
          </li>
          <li>
            <a alt="#doc" class="tab_menu"> Documents </a>
          </li>
          <li>
            <a alt="#ad" class="tab_menu"> Nos annonces </a>
          </li>
        </ul>
      </div>

      <div id="content">
        <div id="form">
          <h4>Ajouter la vidéo - Etape 2</h4>
          <div id="upload_video">
            <%= form_tag @upload_info[:url], :multipart => true do %>
              <div class="field">
                <%= hidden_field_tag :token, @upload_info[:token] %>
              </div>
              <div class="field">
                <%= label_tag "Fichier" %>
                <%= file_field_tag :file %>
              </div>
              <%= submit_tag "Upload video" %>
            <% end %> 
          </div>
          <div class="clear"></div> 
        </div>

        <div id="communicate" class="tab_content hidden">
          <div class="write_msg">
            <% if current_user.url_img != nil%>
              <a href="<%= user_path(current_user) %>"><%= image_tag current_user.url_img << "=small", :alt => current_user.login, :class => "left" %></a>
            <% else %>
              <a href="<%= user_path(current_user) %>"><%= image_tag current_user.avatar.url(:small), :class => "left" %></a>
            <% end %>
            <%= form_for(@project) do |f| %>
              <%= f.text_area :message, :value => "Rédiger un message..." %>
            <% end %>
          </div>
        </div>

        <div id="doc" class="tab_content hidden">
          <p>documents</p>
        </div>

        <div id="ad" class="tab_content hidden">
          <% admin = false %>
          <% members = @project.users.where("admin = ?", true) %>
          <% for member in members %>
            <% if member.id == current_user.id %>
              <% admin = true %>
            <% end %>
          <% end %>
          <% if admin == true %>
            <%= render :partial => "announces/new", :locals => {:@announce => Announce.new, :@author_type => '1', :@author_id => @project.id} %>
          <% end %>
          <div class="clear"></div>
          <%if !@announces.blank?%>
              <div id="announces">
                  <h4>Mes annonces</h4>
                    <% for announce in @announces %>
                      <% candidates = AnnounceCandidate.where("announce_id = ?", announce.id) %>
                      <% singular_sentence = "candidat a postulé" %>
                      <% plural_sentence = "candidats ont postulé" %>
                      <% negative_sentence = "Aucun candidat n'a postulé" %>
                      <% if candidates.count == 0 %>
                        <% sentence = negative_sentence %>
                      <% elsif candidates.count == 1 %>
                        <% sentence = "#{candidates.count} " << singular_sentence %>
                      <% else %>
                        <% sentence = "#{candidates.count} " << plural_sentence %>
                      <% end %>
                      <% available = false %>
                      <% for candidate in candidates %>
                        <% if candidate.accepted %>
                          <% available = true %>
                        <% end %>
                      <% end %>
                      <% idcss = "#{announce.id}" %>

                      <div class="announce">
                          <a href="<%= project_path(@project) %>">
                            <%= image_tag @project.avatar_project.url(:medium), :class => "left"%>
                          </a>
                          <p class="send_mail"><img src="#" alt=""/>
                            <% if candidates.count > 0 && available == false%>
                              <%= link_to sentence, "##{announce.id}", :class => "popup" %>
                            <% elsif available == true %>
                              <span class="left">Pourvu</span>
                            <% else %>
                              <%= sentence %>
                            <% end %>
                          </p>
                          <div>
                            <h3><%= announce.title%></h3>
                            <% job = Job.find(announce.job_id) %>
                            <p>
                                <span>#<%= job.label %></span>
                            </p>
                            <p>
                                <img src="/img/icons/location.png" alt=""/>
                                <span><%= announce.location %></span>
                            </p>
                            <p class="description"><%= announce.description %></p>
                            <div class="clear"></div>
                          </div>
                      </div>
                      <% if candidates.count > 0 %>
                        <div style="display: none;">
                          <div id="<%= idcss %>" class="manage_candidates">
                            <%= render :partial => "announces/candidates", :locals => {:@announce_id => announce.id}%>
                          </div>
                        </div>
                      <% end %>
                      <div class="clear"></div>
                    <% end %>
            </div>
          <% end %>
        </div>

      </div>
    </div>
    <div class="clear"></div>
  </div>
</div>