config/routes.rb
Schizoworld::Application.routes.draw do

  resources :announces
  resources :messages

  match '/activate/:activation_code' => 'users#activate', :as => :activate, :activation_code => nil

  resource :session, :only => [:new, :create, :destroy, :provider, :failure]
  resources :sessions
  resources :users
  resources :projects do
    resources :posts
  end
  
  resources :videos do
  member do
    post :add_comment
  end
  new do
     post :upload
     get :save_video
   end
  end

  match "videos/:id/add_comment", :to => "videos#add_comment"

  match 'login' => 'sessions#new', :as => :login
  match 'logout' => 'sessions#destroy', :as => :logout
  match 'signup' => 'users#new', :as => :signup
  match 'register' => 'users#create', :as => :register

  match '/auth/:provider/callback', :to => 'sessions#provider'
  match '/auth/failure', :to => 'sessions#failure'

  match 'profile' => 'users#index', :as => :profile

  match '/messages' => 'messages#create', :via => :post
  match '/messages', :to => 'messages#inbox'
  get 'messages/autocomplete_user_login'
  match '/messages/show/:id', :to => 'messages#show'
  match '/messages/inbox', :to => 'messages#inbox'
  match '/messages/sentbox', :to => 'messages#sentbox'
  match '/messages/trash', :to => 'messages#trash'
  match '/messages/new', :to => 'messages#new'
  
  match ':controller(/:action(/:id(.:format)))'
  
  root :to => "application#index"

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :announces, :foreign_key => "author_id"
  has_many :announce_candidates, :foreign_key => "author_id"
	has_many :project_users
  has_many :users, :through => :project_users
  has_many :job_users
  has_many :jobs, :through => :job_users
  has_many :posts

  has_attached_file :avatar_project, :styles => { :large => "180x180#", :medium => "100x100#", :small => "50x50#", :thumb => "30x30#" }

  attr_accessible :name, :description, :city, :avatar_project
  

  def self.search(search)
    if search
      find(:all, :conditions => ['name LIKE ?', "%#{search}%"])
    else
      find(:all)
    end
  end
  
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find(params[:id])
    @post = Post.new
    @announces = Announce.where("author_id = ? AND author_type = ?", @project.id, '1')
 
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.json
  def new
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
  end
  
  def adduser
    @project = Project.find(params[:id])
    user_to_add = User.find(params[:iduser])
    if not @project.users.include?(user_to_add)
      ProjectUser.create(:project => @project, :user => user_to_add, :admin => false)
    end
    redirect_to @project
  end
  
  def destroyuser
    @project = Project.find(params[:id])
    user_to_destroy = User.find(params[:iduser])
    @project.users.delete(user_to_destroy)
    redirect_to @project
  end
  
  def promoteuser
    @project = Project.find(params[:id])
    user_to_promote = User.find(params[:iduser])
    ProjectUser.find_by_project_id_and_user_id(@project,user_to_promote).update_attribute(:admin, true)
    redirect_to @project
  end

  def addcandidateuser
    @project = Project.find(params[:id])
    user_to_add = User.find(params[:iduser])
    if not @project.users.include?(user_to_add)
      ProjectUser.create(:project => @project, :user => user_to_add, :admin => false)
    end
    candidate = AnnounceCandidate.find_by_announce_id_and_author_id(params[:idannounce], params[:iduser])
    candidate.update_attribute(:accepted, true)
    candidate.save
    redirect_to @project
  end

  def addcandidateproject
    @project = Project.find(params[:id])
    user_to_add = User.find(params[:iduser])
    if not @project.users.include?(user_to_add)
      ProjectUser.create(:project => @project, :user => user_to_add, :admin => false)
    end
    candidate = AnnounceCandidate.find_by_announce_id_and_author_id(params[:idannounce], params[:id])
    candidate.update_attribute(:accepted, true)
    candidate.save
    redirect_to @project
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(params[:project])
    @project.status = "Etat zero"
    creator = current_user
    ProjectUser.create(:project => @project, :user => creator, :admin => true)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    @project.users.delete_all

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end
  
  def addjob
    @project = Project.find(params[:id])
    @user = User.find(params[:project][:user_id])
    
    if not (params[:user_job][:job_id].empty?)
      job = Job.find(params[:user_job][:job_id])
      if not @project.jobs.where("user_id = ?", @user.id).include?(job)
        JobUser.create(:project_id => @project.id, :job_id => job.id, :user_id => @user.id)
      end
    end
    
    redirect_to edit_project_path, notice: 'Job was successfully added.'
  end
  
  def destroyjob
    @project = Project.find(params[:id])
    @user = User.find(params[:iduser])
    job_to_destroy = Job.find(params[:idjob])
    JobUser.where("project_id = ? AND user_id = ? AND job_id = ?",@project.id, @user.id, job_to_destroy.id).delete_all
    redirect_to edit_project_path(@project)
  end
    
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label "Avatar" %>
    <%= f.file_field :avatar_project %>
  </div>
  <br/>
  <div class="field">
    <%= f.label :description %><br/>
    <%= f.text_area :description %>
  </div>

  <div class="actions">
    <%= f.submit 'Mettre à jour le projet'%>
  </div>
<% end %>

app/views/projects/_formCreation.html.erb
<%= form_for(@project, :url => projects_path(:iduser => @user.id)) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :avatar_project %>
    <%= f.file_field :avatar_project %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/_formJob.html.haml
= form_for @project, :html => { :multipart => true }, :url => {:action => "addjob", :id => @project} do |f|
  -if @project.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg

  .field
    = collection_select(:user_job, :job_id, Job.all, :id, :label, :prompt => 'Sélectionner un job')
  .field
    = f.hidden_field(:user_id, :value => iduser)
  .actions
    = f.submit 'Ajouter un job'

app/views/projects/_new.html.erb
<div class="subscription popup_login">
  <div id="signup" class="login">
    <h1>Create a new project</h1>

    <%= form_for(@project, :url => projects_path(:iduser => @user.id)) do |f| %>
      <% if @project.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

          <ul>
          <% @project.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <%= f.label :name %>
        <%= f.text_field :name %>
      </div>
      <div class="field">
        <%= f.label :city %>
        <%= f.text_field :city %>
      </div>
      <div class="field">
        <%= f.label :description %><br/>
        <%= f.text_area :description %>
      </div>
      <div class="field">
        <%= f.label "Avatar" %>
        <%= f.file_field :avatar_project %>
      </div>

      <div class="actions">
        <%= f.submit %>
      </div>
    <% end %>
  </div>
</div>

app/views/projects/_privateProject.html.erb
<div id="sky">
  <div id="container" class="socialContainer">
    <a href="<%= project_path(@project) %>"><%= image_tag @project.avatar_project.url(:large), :class => "img_sheet" %></a>
    <h1><a href="<%= project_path(@project) %>"><%= @project.name %></a></h1>

    <div class="left info_sup">
      <% admin = false %>
      <% members = @project.users.where("admin = ?", true) %>
      <% for member in members %>
        <% if member.id == current_user.id %>
          <% admin = true %>
        <% end %>
      <% end %>
      <% if admin == true %>
        <div class="info">
          <img src="/img/icons/pencil.png" alt="" class="left"/>
          <p><%=link_to 'Editer la fiche projet', edit_project_path(@project)%></p>
        </div>
        <div class="info">
          <img src="/img/icons/file.png" alt="" class="left"/>
          <p><%=link_to 'Voir la fiche publique', :controller => "projects", :action => "show", :public => true%></p>
        </div>
        <% video = Video.where("project_id = ?", @project.id) %>
        <% if video.blank? %>
          <div class="info">
            <img src="/img/icons/film.png" alt="" class="left"/>
            <p><%=link_to 'Ajouter la vidéo', :controller => "videos", :action => "new", :project_id => @project.id%></p>
          </div>
        <% end %>
        <br/><br/>
      <% end %>

      <% if @project.city %>
        <div class="info">
          <img src="/img/icons/location.png" alt="" class="left"/>
          <p><%= @project.city %></p> 
        </div>
      <%end%>

      <% if @project.status %>
        <div class="info">
          <img src="/img/icons/process.png" alt="" class="left"/>
          <p><%= @project.status %></p> 
        </div>
      <%end%>  
      <br/>
      
      <div class="project_members">
        <% for user in @project.users %>
            <% if user.url_img != nil%>
              <a href="<%= user_path(user) %>"><%= image_tag user.url_img << "=small", :alt => user.login, :class => "left thumb_facebook" %></a>
            <% else %>
              <a href="<%= user_path(user) %>"><%= image_tag user.avatar.url(:thumb), :class => "left" %></a>
            <% end %>
            <p class="left"><a href="<%= user_path(user) %>"><%= user.login %></a></p>
            <div class="clear"></div>
        <% end %> 
      </div> 
    </div>

    <div class="right" id="social_content">
          <div id="socialMenu">
            <ul id="tabs">
              <li class="active">
                <a alt="#communicate" class="tab_menu"> Communiquer </a>
              </li>
              <!--<li>
                <a alt="#doc" class="tab_menu"> Documents </a>
              </li>-->
              <li>
                <a alt="#ad" class="tab_menu"> Nos annonces </a>
              </li>
            </ul>
          </div>
          <div id="content">
            <p id="notice"><%= notice %></p>

            <div id="communicate" class="tab_content">
              <%= render :partial => "posts/new", :locals => {:@project_id => @project.id} %>
              <div id="posts">
                <% @project.posts.latest.each do |p| -%>
                  <%= render :partial => "posts/show", :locals => {:@post => p} %>
                <% end -%>
              </div>
            </div>

            <div id="doc" class="tab_content hidden">
              <p>documents</p>
            </div>

            <div id="ad" class="tab_content hidden">
              <% admin = false %>
              <% members = @project.users.where("admin = ?", true) %>
              <% for member in members %>
                <% if member.id == current_user.id %>
                  <% admin = true %>
                <% end %>
              <% end %>
              <% if admin == true %>
                <%= render :partial => "announces/new", :locals => {:@announce => Announce.new, :@author_type => '1', :@author_id => @project.id} %>
              <% end %>
              <div class="clear"></div>
              <%if !@announces.blank?%>
                  <div id="announces">
                      <h4>Mes annonces</h4>
                        <% for announce in @announces %>
                          <% candidates = AnnounceCandidate.where("announce_id = ?", announce.id) %>
                          <% singular_sentence = "candidat a postulé" %>
                          <% plural_sentence = "candidats ont postulé" %>
                          <% negative_sentence = "Aucun candidat n'a postulé" %>
                          <% if candidates.count == 0 %>
                            <% sentence = negative_sentence %>
                          <% elsif candidates.count == 1 %>
                            <% sentence = "#{candidates.count} " << singular_sentence %>
                          <% else %>
                            <% sentence = "#{candidates.count} " << plural_sentence %>
                          <% end %>
                          <% available = false %>
                          <% for candidate in candidates %>
                            <% if candidate.accepted %>
                              <% available = true %>
                            <% end %>
                          <% end %>
                          <% idcss = "#{announce.id}" %>

                          <div class="announce">
                              <a href="<%= project_path(@project) %>">
                                <%= image_tag @project.avatar_project.url(:medium), :class => "left"%>
                              </a>
                              <p class="send_mail"><img src="#" alt=""/>
                                <% if candidates.count > 0 && available == false%>
                                  <%= link_to sentence, "##{announce.id}", :class => "popup" %>
                                <% elsif available == true %>
                                  <span class="left">Pourvu</span>
                                <% else %>
                                  <%= sentence %>
                                <% end %>
                              </p>
                              <div>
                                <h3><%= announce.title%></h3>
                                <% job = Job.find(announce.job_id) %>
                                <p>
                                    <span>#<%= job.label %></span>
                                </p>
                                <p>
                                    <img src="/img/icons/location.png" width="13px" alt=""/>
                                    <span><%= announce.location %></span>
                                </p>
                                <p>
                                    <img src="/img/icons/calendar_empty.png" width="20px" alt=""/>
                                    <span><%= announce.date %></span>
                                </p>
                                <p class="description"><%= announce.description %></p>
                                <div class="clear"></div>
                              </div>
                          </div>
                          <% if candidates.count > 0 %>
                            <div style="display: none;">
                              <div id="<%= idcss %>" class="manage_candidates">
                                <%= render :partial => "announces/candidates", :locals => {:@announce_id => announce.id}%>
                              </div>
                            </div>
                          <% end %>
                          <div class="clear"></div>
                        <% end %>
                </div>
              <% end %>
            </div>

              <!--<h4>Liste des administrateurs</h4>
              <% for user in @project.users.where("admin = ?", true) %>
                    -<%= user.login %>
                    <br/>
              <% end %>

              <h4>Liste des non-administrateurs</h4>
              <% for user in @project.users.where("admin = ?", false) %>
                    -<%= user.login %>
                    
                    <% if @project.users.where("admin = ?", true).include? (current_user) %>          
                      -<%= link_to "Promote", {:controller => "projects", :action => "promoteuser", :id => @project.id, :iduser => user.id} %>
                      -<%= link_to "Delete", {:controller => "projects", :action => "destroyuser", :id => @project.id, :iduser => user.id} %>
                    <%  end %>
                      
                    <br/>
              <% end %>
              
              <% if @project.users.where("admin = ?", true).include? (current_user) %>          
              <h4>Ajouter des utilisateurs au groupe</h4>
                <p>
                    <% for user in User.all %>
                      <%= link_to user.login, {:controller => "projects", :action => "adduser", :id => @project.id, :iduser => user.id} %>
                      <br/>
                  <% end %>
                </p>
                    
                <%= link_to 'Edit', edit_project_path(@project) %> |
                <%= link_to 'Back', projects_path %>
              <% end %>-->
          </div>
    </div>
    <div class="clear"></div>
  </div>
</div>

app/views/projects/_publicProject.html.erb
<div id="sky">
  <div id="container" class="socialContainer">
    <% if !current_user.nil? %>
      <a href="<%= project_path(@project) %>"><%= image_tag @project.avatar_project.url(:large), :class => "img_sheet" %></a>
    <% else %>
      <%= image_tag @project.avatar_project.url(:large), :class => "img_sheet" %>
    <% end %>
    <h1>
      <% if !current_user.nil? %>
        <a href="<%= project_path(@project) %>"><%= @project.name %></a>
      <% else %>
        <%= @project.name %>
      <% end %>
    </h1>

    <div class="left info_sup">
      <% if @project.city %>
        <div class="info">
          <img src="/img/icons/location.png" alt="" class="left"/>
          <p><%= @project.city %></p> 
        </div>
      <%end%>

      <% if @project.status %>
        <div class="info">
          <img src="/img/icons/process.png" alt="" class="left"/>
          <p><%= @project.status %></p> 
        </div>
      <%end%>  
      <br/><br/>

      <div class="project_members">
        <% for user in @project.users %>
            <% if user.url_img != nil%>
              <a href="<%= user_path(user) %>"><%= image_tag user.url_img << "=small", :alt => user.login, :class => "left thumb_facebook" %></a>
            <% else %>
              <a href="<%= user_path(user) %>"><%= image_tag user.avatar.url(:thumb), :class => "left" %></a>
            <% end %>
            <p class="left"><a href="<%= user_path(user) %>"><%= user.login %></a></p>
            <div class="clear"></div>
        <% end %> 
      </div>       

    </div>

    <div class="right" id="social_content">
      <div id="socialMenu">
        <ul id="tabs">
          <li class="active">
            <a alt="#project_video" class="tab_menu"> Vidéo </a>
          </li>
          <li>
            <a alt="#project_description" class="tab_menu"> Description </a>
          </li>
          <li>
            <a alt="#ad" class="tab_menu"> Leurs annonces </a>
          </li>
        </ul>
      </div>

      <div id="content">
        <p id="notice"><%= notice %></p>
        <div id="project_video" class="tab_content">
          <% @video = Video.first(:conditions => {:project_id => @project.id}) %>
          <% if !@video.blank? %>
            <%= render :partial => "videos/show", :locals => {:video => @video, :project => @project } %>
          <% else %>
            <p>Aucune vidéo n'a encore été postée</p>
          <% end %>
        </div>

        <div id="project_description" class="tab_content hidden">
          <p><%= @project.description %></p>
        </div>

        <div id="ad" class="tab_content hidden">
          <%if !@announces.blank?%>
            <div id="announces">
                <h4>Mes annonces</h4>
                  <% for announce in @announces %>
                    <% candidates = AnnounceCandidate.where("announce_id = ?", announce.id) %>
                    <% available = false %>
                    <% for candidate in candidates %>
                      <% if candidate.accepted %>
                        <% available = true %>
                      <% end %>
                    <% end %>
                    <% idcss = "#{announce.id}" %>

                    <div class="announce">
                        <a href="<%= project_path(@project) %>">
                          <%= image_tag @project.avatar_project.url(:medium), :class => "left"%>
                        </a>
                        <p class="send_mail"><img src="#" alt=""/>
                          <% candidates = AnnounceCandidate.where("announce_id = ?", announce.id) %>
                          <% postulated = false %>
                          <% if !current_user.nil? %>
                            <% for candidate in candidates %>
                              <% if candidate.author_id == current_user.id %>
                                <% postulated = true %>
                              <% end %>
                            <% end %>
                          <% end %>
                          <% if postulated == false %>
                            <% if announce.author_type == 1 %>
                              <p class="send_mail">
                                <img src="#" alt=""/>
                                <%= link_to "Postuler", :action => "postuleruser", :id => current_user.id, :announce_id => announce.id %>
                              </p>
                            <% end %>
                          <% end %>
                          <% if available == true %>
                            <span class="left">Pourvu</span>
                          <% end %>
                        </p>
                        <div>
                          <h3><%= announce.title%></h3>
                          <% job = Job.find(announce.job_id) %>
                          <p>
                              <span>#<%= job.label %></span>
                          </p>
                          <p>
                              <img src="/img/icons/location.png" width="13px" alt=""/>
                              <span><%= announce.location %></span>
                          </p>
                          <p>
                              <img src="/img/icons/calendar_empty.png" width="20px" alt=""/>
                              <span><%= announce.date %></span>
                          </p>
                          <p class="description"><%= announce.description %></p>
                          <div class="clear"></div>
                        </div>
                    </div>
                    <% if candidates.count > 0 %>
                      <div style="display: none;">
                        <div id="<%= idcss %>" class="manage_candidates">
                          <%= render :partial => "announces/candidates", :locals => {:@announce_id => announce.id}%>
                        </div>
                      </div>
                    <% end %>
                    <div class="clear"></div>
                  <% end %>
            </div>
          <% end %>
        </div>


        <!--<h4>Liste des administrateurs</h4>
        <% for user in @project.users.where("admin = ?", true) %>
              -<%= user.login %>
              <br/>
        <% end %>

        <h4>Liste des non-administrateurs</h4>
        <% for user in @project.users.where("admin = ?", false) %>
              -<%= user.login %>
              <br/>
        <% end %>-->
      </div>
    </div>
    <div class="clear"></div>
  </div>
</div>

app/views/projects/index.html.erb
<h1>Listing projects</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>State</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @projects.each do |project| %>
  <tr>
    <td><%= project.name %></td>
    <td><%= project.description %></td>
    <td><%= project.city %></td>
    <td><%= link_to 'Show', project %></td>
    <td><%= link_to 'Edit', edit_project_path(project) %></td>
    <td><%= link_to 'Destroy', project, :confirm => 'Are you sure?', :method=> :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<div id="sky">
  <div id="container" class="socialContainer">
    <a href="/profile">
      <img class="img_sheet" src="<%= @user.avatar.url(:large) %>" alt="<%= @user.login %>"/>
    </a>
    <h1><%= link_to @user.login, user_path(@user) %></h1>

    <div class="left info_sup">
      <%=link_to 'Editer la fiche projet', edit_user_path(@user)%>

      <% if @user.location %>
        <p><%= @user.location %></p>
      <% end %>
 
 <!-- <%= render 'form' %>-->

      <% if @user.status %>
        <p><%= @user.status %></p>
      <% end %>

    </div>

    <div id="social_content" class="right">
      <div id="socialMenu">
        <ul id="tabs">
          <li class="active">
            <a href="#"> Communiquer </a>
          </li>
          <li>
            <a href="#"> Documents </a>
          </li>
          <li>
            <a href="#"> Annonces </a>
          </li>
        </ul>
      </div>

      <div id="content">
		  <h1>New project</h1>
		  <%= render 'formCreation' %>
	  </div>
    </div>
    <div class="clear"></div>
  </div>
</div>

</div>

app/views/projects/show.html.erb
  <% if ((@project.users.include? (current_user)) && (!params.has_key?(:public))) %>
    <%= render 'privateProject' %>
  <% else %>
    <%= render 'publicProject' %>
  <% end %>
  <!--if (@project.users.include? (current_user) && params[:public] == true )-->